### ISSUE TITLE
Running the navigation-app created by "yo aurelia" results with error messages

### ISSUE THREAD

**Issue by adriatic** [aurelia/documentation#145]
command ``gulp watch`` applied to the app described [here](https://github.com/aurelia/documentation/blob/master/English/get-started.md#setting-up-the-project-structure-and-build) results with

```
DEBUG [templating] importing resources for undefined ["nav-bar.html", "bootstrap/css/bootstrap.css"]
aurelia-logging-console.js:38 DEBUG [templating] importing resources for undefined []
aurelia-logging-console.js:38 DEBUG [templating] importing resources for undefined []
```

**Comment by EisenbergEffect** [comment]
Those aren't error message, that's debug output. If it was an error it would say ERROR.
However, it does look like some of the debug information is undefined. That would be a bug in the templating library. I have identified it, fixed it and will push a release shortly.

**Comment by adriatic** [comment]
Perhaps we have a different interpretation of the word "error" - in my careful approach seeing "[templating] importing resources for undefined []" makes me believe that something is not right - whether it is DEBUG output or ERROR. and because I do not see what all could be a consequence of that, I think that it is better to make you aware of it. 

If your explanation "f it was an error it would say ERROR" (which remotely feels like patronizing) tells me that I should not waste our time with such details, I will begin to worry :-)

**Comment by EisenbergEffect** [comment]
At first when I looked at your message, I saw nothing wrong. For many months Aurelia has emitted this debug info. The only thing wrong was the word 'undefined' which should have been the view's id, though that missing parameter wasn't causing any errors. That was hard to see because your error report did not say anything about what you thought was wrong.

In the end, it was just a missing value in the log output. It has been fixed and a new release is now available.

**Comment by adriatic** [comment]
> That was hard to see because your error report did not say anything about what you thought was wrong.

Nice return volley - as I thought that "importing resources for **undefined []**" - was obvious (I wrote too much code in assembler not to be sensitive to word undefined)

**Comment by EisenbergEffect** [comment]
Wasn't obvious to me since I've learned to ignore those DEBUG logs after so many months ;) I just saw the word DEBUG rather than ERROR and didn't think to look deeply into the message, since those messages aren't usually associated with errors at all. In this case, the problem was that the debug information itself wasn't correct.
