### ISSUE TITLE
ESNext example showing ES2015 code

### ISSUE THREAD

**Issue by dinkzilla** [aurelia/documentation#297]
**I'm submitting a bug report**

In the Contact Manager Tutorial documentation, under the section "Building Out the Contact List", when ESNext is selected for the the contact-list.js example, it appears to show the ES2015 code instead.

Below the code example, the documentation notes: 

> In ES 2015, you can declare an inject static method that returns an array of constructor dependencies while in ES Next and TypeScript, you can use an inject decorator to declare those dependencies.

However, in the code example, when ESNext is selected, the code example uses a static inject method, not a decorator:

`static inject() { return [WebAPI] };`

**Comment by michallepicki** [comment]
The same happens with some other examples on this page. I think it may be because they have `<source-code lang="ES Next">` instead of `ES 2016` in markdown source.

Upon inspecting the dropdown button for selecting language with aurelia-context chrome extension, I found out that clicking on `ES Next` sets `currentLanguage` to `ES 2016`.

I looked for source code of documentation hub but couldn't find it. It's not open source? Really? It would be a cool learning resource and an opportunity for aurelia beginners (like me) to contribute. Anyway, my reasoning:

I found this while inspecting with browser:
```
    e.prototype.selectSourceForLanguage = function () {
      var e = this;
      this.currentLanguage = this.language.current;
      for (var t = void 0, n = this.priorities = [
        this.language.current,
        'ES 2015/2016',
        'ES 2015/ES Next',
        'ES 2016/TypeScript',
        'ES 2015/ES 2016/TypeScript',
        'ES 2016',
        'ES 2015',
        'TypeScript',
        'HTML'
      ], i = function (i, o) {
        if (t = e.availableSources.find(function (e) {
          return e.lang === n[i]
        })) return 'break'
      }, o = 0, a = n.length; o < a; ++o) {
        var r = i(o, a);
        if ('break' === r) break
      }
      this.select(t || this.availableSources[0])
    },
```
When current language is `ES 2016` and there's no `ES 2016` in availableSources (because there's `ES Next`) the code for `ES 2015` is being shown.

**Comment by EisenbergEffect** [comment]
We'd love to make it open source, but it needs to be cleaned up quite a bit first. It's a slow, tedious process, but it's being worked on here and there.

**Comment by EisenbergEffect** [comment]
Fixed the fundamental problem in our hub source. Going out with the next hub release.

**Comment by michallepicki** [comment]
any timeframe on when would that be?
