### ISSUE TITLE
Getting Started for Windows users should recommend Git Bash for install

### ISSUE THREAD

**Issue by mtimms** [aurelia/documentation#59]
Attempting to install in Windows 8.1 using the Command Prompt (cmd.exe) or Windows Powershell is a complete exercise in frustration. The jspm install step invariably starts getting timeout errors halfway through, even when you have configured jspm with your GitHub credentials. In contrast I've found the install using Git Bash is fast, smooth and error free.   

The Getting Started process should be necessarily ultra smooth.  There should be a prominent indication in the Getting Started and other docs to recommend a Git Bash install for Windows users..

**Comment by davidpeden3** [comment]
I just recently did the same and had no issues using PowerShell. Technically, I have GitHub for Windows installed with PowerShell selected as my default shell. I would imagine this is how most Windows users will be set up. It might be good to document ways that people _can_ get set up but I don't see any reason to specifically advise using Git Bash without first trying to understand the root cause of the issues that you experienced personally.

**Comment by mtimms** [comment]
I had no issues using PowerShell on the previous release, only on the current one -- .both times running on an Azure VM. i suspect it may have coincided with the last jspm update. It's certainly worth pointing out as an option to avoid a frustrating first time experience for people kicking the Aurelia tires.
